### ISSUE TITLE
Disambiguate the "-5" error code

### ISSUE THREAD

**Issue by brianmcmichael** [blackdotsh/getIPIntel#10]
Hi! Thanks so much for this service, I use it a lot, so much that I'm getting the "-5" response code.

The documentation says "Your connecting IP has been banned from the system or you do not have permission to access a particular service. Did you exceed your query limits? Did you use an invalid email address? If you want more information, please use the contact links below."

It would be nice to have this code split into several other error codes for debugging. For example, I think I've hit my quota, but my server has been hitting your service regularly and I want to make sure I'm not permanently banned for some reason. If the former, I don't need to take further action and can wait until further requests are allocated, if the latter, I would need to email you and beg for forgiveness. Having separate codes for quota usage, invalid contact info, and perma-ban would be helpful on my side.

Thanks!

**Comment by blackdotsh** [comment]
Hi Brian,

Thanks for the suggestion. Usually people that exceed the limit on the free API will get an email in a couple of days letting them know the queries have been exceeded. When it happens, the system will ban that user indefinitely until they enforce the limits required to use the free API and I manually unban them when they contact me. It's done this way because the free API gets a ton of abuse.

The "-5" error basically means you probably need to contact me to get things working again since bans are not automatically removed. You can get banned if you exceed queries, used invalid contact email, etc. This is why "-5" error is pretty broad.
