### ISSUE TITLE
FR: Result Value JSON Description Field

### ISSUE THREAD

**Issue by mitchmoser** [blackdotsh/getIPIntel#16]
I create and maintain an OSINT browser extension for Chrome & Firefox on GitHub called [Sputnik](https://github.com/mitchmoser/sputnik).

We recently got a feature request for an IP lookup to detect VPNs:
https://github.com/mitchmoser/sputnik/issues/14

I’ve been looking into open source tools available for this and came across getIPIntel.
Reviewing the documentation, this seems like a good integration for this feature request.
Looking over the JSON output from an IP search, I noticed there is no description that would be helpful for an uninformed user looking at this information.

Here is an example of what I was looking at:
```
Request:
https://check.getipintel.net/check.php?format=json&contact=test@yahoo.com&oflags=c&flags=b&ip=102.129.239.43

Response:
{
  "status": "success",
  "result": "1",
  "queryIP": "102.129.239.43",
  "queryFlags": "b",
  "queryOFlags": "c",
  "queryFormat": "json",
  "contact": "test@yahoo.com",
  "Country": "US"
}
```

Would it be possible to integrate a description of the result value in the JSON output of a request?

For example:
```
{
  ...
  "result":"1"
  "description":"IP is explicitly banned (a web host, VPN, or TOR node) by our dynamic lists"
   ...
}
{
  ...
  "result":".5"
  "description":"numeric value between 0 and 1 of how likely the IP is bad / VPN / proxy"
  ...
}
```

Thanks for considering this feature request!

**Comment by blackdotsh** [comment]
Hi,

Although I understand your reasoning, I do not plan on adding this feature in the near future. Even though people use json format, some lower level code or other "simple" code that just looks at the specific line(s) without using a proper json parser would cause issues and in those cases, would break their working code.

Since the API is very opened, it's hard to contact everyone and notify them of such an update as well.

If people are looking at the score generated by the API and do not fully understand the meaning, I would direct them to the documentation that's available on the website.
