### ISSUE TITLE
Getting non-json result starting with skipped d

### ISSUE THREAD

**Issue by gruijter** [blackdotsh/getIPIntel#17]
On some requests I get this response (response code is 200):

```skipped d{"status":"success","result":"0","queryIP":"185.94.111.19","queryFlags":"udefied","queryOFlags":"coflags=b","queryFormat":"json","contact":"test@anonymous.com","BadIP":0,"Country":"RU"}```

This is causing my json parser to choke. What does `skipped d` mean, and can I assume this is a bug in the response?

**Comment by blackdotsh** [comment]
Thanks for reporting this, I've since corrected the issue. Let me know if there's any problem still.

Also, when you query the API and you're using flags, it should look something like:

```oflags=bc``` if you want to get the country code and if the IP is considered as bad or not. Sending ```oflags=coflags=b``` isn't correct.

If you're not using ```flags``` option, you don't have to say ```flags=undefined``` just don't put it in the query URL. If you'r explicitly sending the string "undefined" to the API in the request, then it'll take that as a string input and try to apply the "flags" option to it.

**Comment by gruijter** [comment]
Ah, super. I'll change the flags / oflags.

By the way: I'm writing and testing the node NPM package at the moment, and now got a banned message. Could my quota temporarily be increased for the weekend or so?

Thx!

**Comment by blackdotsh** [comment]
Sure. For testing & coding purposes, I've increased the daily limit to 1500 per day for 2 days.
