### ISSUE TITLE
Move to https

### ISSUE THREAD

**Issue by josephmiller2000** [blackdotsh/getIPIntel#9]
If we use your Ip lookup method in our php file, we gonna end up with mixed content warning in chrome browser. So please move your domain over https.

This one >>  http://check.getipintel.net/check.php?ip=IPHere&contact=YourEmailAddressHere

**Comment by blackdotsh** [comment]
I'm not sure what you mean. When you look things up on the API, it's your server (php curl) that's making the request. Based on the results of that request, you display things on your web page accordingly. There shouldn't be any mixed content warning in chrome because at no point would the user (the person that requests your web page) see that you're querying an external API.

What you're describing doesn't sound like the normal use / operation of the API so I'm reluctant to make changes towards the code base. Of course, you're welcome to change the code yourself for your needs provided that you follow the terms of service.

If you can provide more details and reproducible results, I'd be happy to look into this further.
